### ISSUE TITLE
Language used for the documentation

### ISSUE THREAD

**Issue by glihm** [trangnv/cairo-book#2]
Hello!

As I am learning Rust and Cairo recently, I would be very interested to contribute here, and give a very accessible way to new comers to learn Cairo! Very exciting journey. Thank you for this initiative!

It's more a question than an issue, but what about following Starkware initiative to use ascii doc, which provide out of the box a bit more, especially when it comes to mathematical formulas?
But markdown still more widely used in GitHub, that's a point.

What do you think?

**Comment by Cheelax** [comment]
I have no real though as I never used ascii doc, might be worth a try

**Comment by glihm** [comment]
Never used it too, but I am discovering it with Starkware documentation and it's interesting. :)

Anyway, @trangnv as you mentioned it's highly preferable to stick to something you like in this kind of project, I'll follow your initiative with md and mdbook then. 👍 

Thank you both for you time answering this.
